name: Deploy to GitHub Pages

on:
  push:
    branches: 
      - main

jobs:
  deploy-to-github-pages:

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install wasm-tools for AOT compilation
      run: dotnet workload install wasm-tools

    - name: Publish Frontend project
      run: dotnet publish src/Frontend/Frontend.csproj -c Release -o release --nologo
    
    - name: Change base-tag in index.html from / to PrimeView
      run: sed -i 's/<base href="\/" \/>/<base href="\/PrimeView\/" \/>/g' release/wwwroot/index.html
    
    - name: Copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    - name: Remove Azure static web app config
      run: rm release/wwwroot/staticwebapp.*

    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: pages
        FOLDER: release/wwwroot
